### ISSUE TITLE
Another work related to SAM

### ISSUE THREAD

**Issue by Eli-YiLi** [PengtaoJiang/Segment-Anything-CLIP#1]
Hi, I see you are planing to add maskclip.

There is another work beyond MaskCLIP and suits SAM fine, in the aspect of CLIP's explainability: https://github.com/xmed-lab/CLIP_Surgery

It's able to guide SAM to achieve text to mask without manual points. Besides, it enhances many open-vocabulary tasks, like segmentation, multi-label classification, multimodal visualization.

This is the jupyter demo:
https://github.com/xmed-lab/CLIP_Surgery/blob/master/demo.ipynb

This is our segmentation results:
![image](https://user-images.githubusercontent.com/49093246/232215782-3caac15b-e646-4bde-8b1d-ffedb96f20a1.png)

This is our heatmap:
![image](https://user-images.githubusercontent.com/49093246/232216182-8a77793a-1090-4821-9722-57f077b7a182.png)

**Comment by PengtaoJiang** [comment]
Hello, @Eli-YiLi , great work! I will give your project a link in README.
